from .etsi_vnf_content import EtsiVnfContentHandler, EtsiVnfPkgContentTree
from .etsi_vnf_src import EtsiVnfSourceHandler, EtsiVnfSourceCreator

source_creator = EtsiVnfSourceCreator
source_handler = EtsiVnfSourceHandler
content_handler = EtsiVnfContentHandler