---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: lmctl.log # Will be replaced with ~/.lmctl directory
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    lmctl:
        level: INFO
        handlers: [file_handler]
        propagate: yes
root:
    level: INFO
    handlers: [file_handler]
