branches:
  only:
  - main
  - develop
  - "/^support\\/.*$/"
language: python
dist: bionic
python:
- '3.8'
- '3.9'
- '3.10'
install:
- pip install -U importlib_metadata # Workaround issues on Python3.7 (for travis only) - https://travis-ci.community/t/build-error-for-python-3-7-on-two-different-projects/12895
- pip install .
script:
- python3 -m unittest discover -s tests.unit
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: h7kWp7crWanRkd3BptT6fiGLn5uSRQj0BH+/nyVII0+RUYMLN2CoM+c4vFJT/BAlP/y1jLHMboTB3RRQwem8DjEa2Is5xp31ekg03dW8IBiG7P237QvY98gsdi2yXXwaQcOQ8YdyaKKHEGOpmVluWHuWKOSPIEKxW/lP4Yss9xOl04NVGNNFC/U+dkVuFjuSfLn15Se6SGXR6kOIv97a/ZjqBoG0Sv9TXcUrCS6pHIkHHrhlMpem9yvAB18d51DRfckafTWFsD5SpaV2SVamuowyMZDi8BnLqi5ezQcmBHMPnuiXuOygTcVUARpy+q/g9tFzCh8DuOnTTDeWRgM0jUjRbAfL/B8H0EbUGF85fL2VDilMT9K37D7vai+FiyE+3p1u7gv6XChG7yicX7u38ROU47QLrAT1vMahBauxMxX7hDqMEGnJsHV9K5j7i8RP79ZeSw7BmoSmaV74WObGfFnxKtxudgRz21fduBnaWDFIPiIGls51R6o9f2qoqA92IqL6JQ+6hsoCC6en9D/H+X/PrnggL6IbN3seolojkDd7l2iPU+9GxQwGPp1a3b7mkVf8iQzPzO24EG2rRoPKzr8HHIwvivr3td6L50A0kkY9lAH6btZ+CZ9IIqJF6TTQLRi/wQ6V+Gk+krL2CKb87OzLbke5VbAtuZ1vTkqErhY=
