from .assembly_content import AssemblyContentHandler
from .assembly_src import AssemblySourceHandler, AssemblySourceCreator

source_creator = AssemblySourceCreator
source_handler = AssemblySourceHandler
content_handler = AssemblyContentHandler